name: Generate Snake Animation

on:
  schedule:
    # Atualiza diariamente às 23:59
    - cron: "59 23 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório
      - uses: actions/checkout@v3

      # Geração da animação da cobrinha
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: crisz-source
          outputs: dist/snake.svg

      # Publicação do arquivo no branch "output"
      - name: Push Snake Animation to output branch
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
